name: Run Mage

on:
  # TODO

jobs:
  mage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16 # TODO

      - name: Run Mage
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: -v yourTargetsHere