name: Get tag version

on:
  release:

jobs:
  tag_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get tag version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//} # then use ${{ steps.get_version.outputs.VERSION }}
