version: "3.7"

services:
    db:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            - MYSQL_USER=username
            - MYSQL_PASSWORD=password
            - MYSQL_ROOT_PASSWORD=rootpassword
        volumes:
            - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql

    application:
        build: .
        ports:
            - 30001:80
        depends_on:
            - db